typedef NS_ENUM(uint8_t, RKAsyncId) {
    RKAsyncIdPowerNotifications = 0x01,
    RKAsyncIdLevel1DiagnosticResponse = 0x02,
    RKAsyncIdSensorDataStreaming = 0x03,
    RKAsyncIdConfigBlockContents = 0x04,
    RKAsyncIdPreSleepWarning = 0x05,
    RKAsyncIdMacroEmitMarker = 0x06,
    RKAsyncIdCollisionDetected = 0x07,
    RKAsyncIdOrbBasicPrint = 0x08,
    RKAsyncIdOrbBasicErrorASCII = 0x09,
    RKAsyncIdOrbBasicErrorBinary = 0x0A,
    RKAsyncIdSelfLevelComplete = 0x0B,
    RKAsyncIdGyroRangeExceeded = 0x0C,
    RKAsyncIdSoulDataResponse = 0x0D,
    RKAsyncIdSoulLevelUpNotification = 0x0E,
    RKAsyncIdSoulShieldNotification = 0x0F,
    RKAsyncIdBoostNotification = 0x11,
    RKAsyncIdOvalErrorBroadcast = 0x12,
    RKAsyncIdOvalDeviceBroadcast = 0x13,
    RKAsyncIdDidSleep = 0x14,
    RKAsyncIdLevel1DiagnosticChunkedResponse = 0x15,
    RKAsyncIdSoulBlockData = 0x20,
    RKAsyncIdXPUpdateEvent = 0x21
};