//
//  Copyright (c) 2014 Orbotix Inc. All rights reserved.
//

#import <RobotCommandKit/RKAsyncMessage.h>

/*!
 * Class to encapsulate asyncronous messages sent from a Sphero. 
 */
@interface RKOrbBasicErrorASCII : RKAsyncMessage


/*! Error message that was generated by orbbasic. */
@property ( nonatomic, readonly ) NSString *error;

@end
